"""Build auditable species-direct packages from structured flora and breeding sources.

The adapters intentionally keep the source trait (not merely the three-axis
summary), exact source excerpt, accepted-name identity, and original-source
lineage.  Existing direct species x trait pairs are omitted so the package is
an incremental acquisition batch.  NHM ADEPT redistributions of eFloras are
assigned the original eFloras treatment lineage whenever it is already known,
preventing a provider mirror from becoming an independent source.

This module creates deterministic audit *templates*.  Review decisions are not
generated by the acquisition code and must be completed separately.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

from analysis.prepare_nhm_adept_bhl_source_package_20260808 import _extract_record
from island_v2.integrated_trait_coverage import EVIDENCE_COLUMNS

CREATED_DATE = "2026-08-08"
AUDIT_RANDOM_STATE = 20260808
BASEFLOR_SHA256 = "ffdb16bc5f9ca45b94994ba2205cc8c0661bf1c306bffd71c1c3ff2cff40629b"
FLORAWEB_SHA256 = "a32b5779b2d7a92284fdfdf0f77ec5a7364283bb9a8f277009d6e29116e12382"
PFAF_SHA256 = "668547d19b1d4dcad7e3d688d17bd9c1882d3732d7c6c2974dad3e46aae37fd6"
KEN_FERN_SHA256 = "7014b8d4d6686bc17d2b087337e0e0a61f782c07a0a9687af2d2173076074572"
TREE_OF_SEX_SHA256 = "8271439fc044f295483156b20d5f72f832635f0046af9c6b970ccfcdfba7ff0a"
ALIEN_PLANTS_AUTOGAMY_SHA256 = "23ed2c727ba1e1457146412161db272ea7989d0f2f923964b61b9e53b9656011"

NHM_RESOURCES = {
    "flora_of_china": {
        "resource_id": "6537b171-c40e-4936-90bd-f1cd4f9697e7",
        "provider": "nhm_adept_flora_of_china_2026",
        "citation": "Flora of China, redistributed as structured traits by Araujo, Hartley & Brummitt (2026), DOI 10.5519/p3dm31kc",
        "efloras_provider": "efloras:2",
    },
    "flora_of_north_america": {
        "resource_id": "dd2dccaf-8cd1-4091-940c-a505ae6cb03f",
        "provider": "nhm_adept_flora_of_north_america_2026",
        "citation": "Flora of North America, redistributed as structured traits by Araujo, Hartley & Brummitt (2026), DOI 10.5519/p3dm31kc",
        "efloras_provider": "efloras:1",
    },
    "flora_of_pakistan": {
        "resource_id": "265a930d-a80f-4e46-b82d-0d36141d17ce",
        "provider": "nhm_adept_flora_of_pakistan_2026",
        "citation": "Flora of Pakistan, redistributed as structured traits by Araujo, Hartley & Brummitt (2026), DOI 10.5519/p3dm31kc",
        "efloras_provider": "",
    },
}

COLOUR_MAP = {
    "blanc": "white",
    "jaune": "yellow_orange",
    "rose": "red_pink",
    "vert": "green_brown_inconspicuous",
    "marron": "green_brown_inconspicuous",
    "bleu": "blue_purple",
    "noir": "other_described",
}


def _text(value: object) -> str:
    if value is None or pd.isna(value):
        return ""
    return " ".join(str(value).strip().split())


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _id(*parts: str) -> str:
    payload = "|".join(parts)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:24]


def _record(
    *,
    species: str,
    trait: str,
    axis: str,
    value: str,
    provider: str,
    url: str,
    source_key: str,
    citation: str,
    excerpt: str,
    lineage: str,
    lineage_method: str,
    source_artifact: str,
    source_file: str,
    quality: str = "high",
    name_match_method: str = "accepted_name_exact",
    evidence_scope: str = "species_direct",
    acceptance_contract: str = "structured_flora_exact_species_trait_audit_v1",
) -> dict[str, str]:
    return {
        "accepted_species": species,
        "axis": axis,
        "trait_name": trait,
        "normalized_value": value,
        "quality": quality,
        "source_group": "latest_public_web",
        "source_provider": provider,
        "source_url": url,
        "source_record_id": f"scale-{_id(provider, source_key, trait, value)}",
        "source_citation": citation,
        "source_excerpt": excerpt,
        "evidence_scope": evidence_scope,
        "name_match_method": name_match_method,
        "source_lineage": lineage,
        "lineage_method": lineage_method,
        "source_run_id": f"scale-source-acquisition-{CREATED_DATE.replace('-', '')}",
        "source_artifact": source_artifact,
        "source_file": source_file,
        "acceptance_contract": acceptance_contract,
    }


def _current_pairs(lineages: pd.DataFrame) -> set[tuple[str, str]]:
    direct = lineages.loc[
        lineages["quality"].str.casefold().isin({"high", "medium"})
        & lineages["evidence_scope"].str.casefold().isin({"species_direct", "synonym_direct"})
    ]
    return set(zip(direct["accepted_species"], direct["trait_name"], strict=True))


def grassbase_rows(path: Path) -> list[dict[str, str]]:
    source = pd.read_csv(path, dtype=str).fillna("")
    eligible = source.loc[
        source["identity_exact"].str.casefold().eq("true") & source["inflorescence_value"].ne("")
    ]
    rows = []
    for item in eligible.to_dict("records"):
        url = _text(item["source_url"])
        rows.append(
            _record(
                species=_text(item["accepted_species"]),
                trait="inflorescence_display",
                axis="floral_structural_complexity",
                value=_text(item["inflorescence_value"]),
                provider="kew_grassbase",
                url=url,
                source_key=url,
                citation="Royal Botanic Gardens, Kew, GrassBase species description",
                excerpt=_text(item["inflorescence_excerpt"]),
                lineage=f"grassbase:url:{url.casefold()}",
                lineage_method="original_grassbase_species_page",
                source_artifact="kew-grassbase-live-profile-cache-20260808",
                source_file=path.name,
            )
        )
    return rows


def _efloras_existing_map(lineages: pd.DataFrame) -> dict[tuple[str, str], tuple[str, str]]:
    source = lineages.loc[lineages["source_provider"].isin({"efloras:1", "efloras:2"})]
    result: dict[tuple[str, str], tuple[str, str]] = {}
    for item in source.sort_values(["source_provider", "accepted_species", "source_url"]).to_dict(
        "records"
    ):
        result.setdefault(
            (_text(item["source_provider"]), _text(item["accepted_species"])),
            (_text(item["source_lineage"]), _text(item["source_url"])),
        )
    return result


def nhm_efloras_rows(root: Path, lineages: pd.DataFrame) -> list[dict[str, str]]:
    known = _efloras_existing_map(lineages)
    rows: list[dict[str, str]] = []
    for slug, metadata in NHM_RESOURCES.items():
        path = root / f"{slug}_exact_master_records.csv.gz"
        source = pd.read_csv(path, dtype=str).fillna("")
        resource_url = (
            "https://data.nhm.ac.uk/dataset/angiosperm-functional-traits-extracted-"
            f"from-botanical-descriptions/resource/{metadata['resource_id']}"
        )
        for item in source.to_dict("records"):
            species = _text(item["taxon"])
            wfo = _text(item.get("wfo"))
            original = known.get((metadata["efloras_provider"], species))
            source_url = original[1] if original else resource_url
            lineage = original[0] if original else f"efloras:{slug}:{wfo.casefold()}"
            lineage_method = (
                "matched_existing_original_efloras_treatment"
                if original
                else "original_flora_species_treatment_via_wfo_id"
            )
            for extracted in _extract_record(item):
                rows.append(
                    _record(
                        species=species,
                        trait=_text(extracted["trait_name"]),
                        axis=_text(extracted["axis"]),
                        value=_text(extracted["normalized_value"]),
                        provider=metadata["provider"],
                        url=source_url,
                        source_key=f"{metadata['resource_id']}:{_text(item['_id'])}",
                        citation=metadata["citation"],
                        excerpt=_text(extracted["source_excerpt"]),
                        lineage=lineage,
                        lineage_method=lineage_method,
                        source_artifact=f"nhm-adept-resource-{metadata['resource_id']}",
                        source_file=path.name,
                    )
                )
    return rows


def _baseflor_colour(value: str) -> str:
    states = {
        COLOUR_MAP[token.strip().casefold()]
        for token in value.split(",")
        if token.strip().casefold() in COLOUR_MAP
    }
    return "|".join(sorted(states))


def _baseflor_inflorescence(value: str) -> str:
    folded = value.casefold()
    states: set[str] = set()
    if "solitaire" in folded:
        states.add("solitary")
    if any(token in folded for token in ("racème", "panicule", "épi")):
        states.add("raceme_spike_panicle")
    if any(token in folded for token in ("cyme", "ombelle", "corymbe")):
        states.add("umbel_corymb")
    if "capitule" in folded or "capituliforme" in folded:
        states.add("composite_display")
    return "|".join(sorted(states))


def baseflor_rows(path: Path, master_names: set[str]) -> list[dict[str, str]]:
    actual_hash = _sha256(path)
    if actual_hash != BASEFLOR_SHA256:
        raise ValueError(f"Baseflor SHA256 {actual_hash} != pinned {BASEFLOR_SHA256}")
    source = pd.read_excel(path, sheet_name="baseflor", dtype=str).fillna("")
    source = source.loc[source["rang_taxinomique"].eq("esp") & source["nomH"].isin(master_names)]
    taxon_column = source.columns[1]
    url = (
        "https://web.archive.org/web/20231002005253id_/"
        "https://philippe.julve.pagesperso-orange.fr/baseflor.xlsx"
    )
    rows: list[dict[str, str]] = []
    for item in source.to_dict("records"):
        species = _text(item["nomH"])
        taxon_id = _text(item[taxon_column])
        lineage = f"baseflor:species:{species.casefold().replace(' ', '_')}"
        common = {
            "species": species,
            "provider": "baseflor_2023_10",
            "url": url,
            "lineage": lineage,
            "lineage_method": "original_baseflor_species_record",
            "source_artifact": f"baseflor-2023-10-sha256-{BASEFLOR_SHA256}",
            "source_file": path.name,
        }
        colour = _baseflor_colour(_text(item["couleur_fleur"]))
        if colour:
            rows.append(
                _record(
                    **common,
                    trait="flower_primary_color",
                    axis="flower_colour",
                    value=colour,
                    source_key=f"{taxon_id}:colour",
                    citation="Julve, Baseflor 2023.10, flower-colour field",
                    excerpt=f"couleur_fleur: {_text(item['couleur_fleur'])}",
                )
            )
        inflorescence = _baseflor_inflorescence(_text(item["inflorescence"]))
        if inflorescence:
            rows.append(
                _record(
                    **common,
                    trait="inflorescence_display",
                    axis="floral_structural_complexity",
                    value=inflorescence,
                    source_key=f"{taxon_id}:inflorescence",
                    citation="Julve, Baseflor 2023.10, inflorescence field",
                    excerpt=f"inflorescence: {_text(item['inflorescence'])}",
                )
            )
        # Baseflor's ``pollinisation`` field describes pollen transfer.  An
        # ``autogame`` token does not establish unassisted fertilisation,
        # fruit set, or seed set, so it cannot populate reproductive assurance.
    return rows


def florabase_rows(path: Path) -> list[dict[str, str]]:
    source = pd.read_csv(path, dtype=str).fillna("")
    source = source.loc[
        source["identity_exact"].str.casefold().eq("true") & source["explicit_colours"].ne("")
    ]
    colour_map = {
        "black": "other_described",
        "blue": "blue_purple",
        "brown": "green_brown_inconspicuous",
        "cream": "white",
        "green": "green_brown_inconspicuous",
        "grey": "other_described",
        "orange": "yellow_orange",
        "pink": "red_pink",
        "purple": "blue_purple",
        "red": "red_pink",
        "violet": "blue_purple",
        "white": "white",
        "yellow": "yellow_orange",
    }
    rows = []
    for item in source.to_dict("records"):
        description = _text(item["supporting_excerpt"])
        flower_clause_match = re.search(r"\bFl\.\s*([^.]*)", description, re.IGNORECASE)
        if not flower_clause_match:
            continue
        flower_clause = flower_clause_match.group(0)
        explicit = [
            token
            for token in _text(item["explicit_colours"]).split("|")
            if re.search(rf"\b{re.escape(token)}(?:ish|y)?\b", flower_clause, re.IGNORECASE)
        ]
        states = {colour_map[token] for token in explicit if token in colour_map}
        if not states:
            continue
        species = _text(item["accepted_species"])
        url = _text(item["profile_url"])
        rows.append(
            _record(
                species=species,
                trait="flower_primary_color",
                axis="flower_colour",
                value="|".join(sorted(states)),
                provider="florabase_western_australia",
                url=url,
                source_key=_text(item["profile_id"]),
                citation="Western Australian Herbarium, FloraBase taxon profile",
                excerpt=flower_clause,
                lineage=f"florabase:profile:{_text(item['profile_id'])}",
                lineage_method="original_florabase_profile_id",
                source_artifact="florabase-live-profile-cache-20260808",
                source_file=path.name,
            )
        )
    return rows


def _floraweb_si(value: str) -> str:
    folded = value.casefold()
    if folded == "selbstkompatibel":
        return "SC"
    if folded == "selbstinkompatibel":
        return "SI"
    if folded in {"± selbstinkompatibel", "± selbstkompatibel"}:
        return "mixed_or_variable"
    return ""


def _floraweb_mating(value: str) -> str:
    return {
        "obligat autogam": "obligate_selfing",
        "fakultativ autogam": "predominantly_selfing",
        "gemischte befruchtung": "mixed_mating",
        "fakultativ xenogam": "predominantly_outcrossing",
        "xenogam": "predominantly_outcrossing",
    }.get(value.casefold(), "")


def _floraweb_form(value: str) -> str:
    folded = value.casefold()
    if "schmetterlingsblumen" in folded or "fabaceentyp" in folded:
        return "papilionaceous"
    if "lippenblumen" in folded:
        return "bilabiate"
    if "stieltellerblumen" in folded:
        return "salverform"
    if "trichterblumen" in folded:
        return "funnel_trumpet"
    if "glockenblumen" in folded:
        return "bell_campanulate"
    if "köpfchenblumen" in folded:
        return "composite_head"
    if "pinsel- und bürstenblumen" in folded:
        return "brush_puff"
    if "violatyp" in folded:
        return "spurred"
    if "scheibenblumen" in folded:
        return "open_radial"
    if any(
        token in folded for token in ("kesselfallenblumen", "klemmfallenblumen", "kolbenblumen")
    ):
        return "other_described"
    return ""


def _floraweb_selfing_trait(value: str) -> tuple[str, str]:
    folded = value.casefold()
    # Pseudocleistogamy is a distinct floral phenomenon and cannot establish
    # presence or absence of true cleistogamy.
    if "pseudokleistogamie" in folded:
        return "", ""
    # BiolFlor section 4.8 records pollen vectors independently from
    # subsequent fertilisation.  Selbstbestäubung therefore cannot establish
    # autonomous reproductive output (including delayed or absent output).
    if "selbstbestäubung" in folded:
        return "", ""
    if "kleistogamie" in folded:
        if folded.startswith("nie "):
            return "cleistogamy", "absent"
        if folded.startswith("unbekannt "):
            return "", ""
        return "cleistogamy", "facultative"
    return "", ""


def floraweb_rows(
    path: Path, eligible_names: set[str]
) -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    actual_hash = _sha256(path)
    if actual_hash != FLORAWEB_SHA256:
        raise ValueError(f"FloraWeb SHA256 {actual_hash} != pinned {FLORAWEB_SHA256}")
    source = pd.read_csv(path, dtype=str).fillna("")
    source = source.loc[source["canonical_name"].isin(eligible_names)].copy()
    strict_rows: list[dict[str, str]] = []
    non_axis_by_species: dict[tuple[str, str], set[str]] = {}
    source_ids: dict[str, str] = {}
    raw_values: dict[tuple[str, str], list[str]] = {}
    for item in source.to_dict("records"):
        species = _text(item["canonical_name"])
        usage_id = _text(item["name_usage_id"])
        label = _text(item["label"])
        raw = _text(item["value"])
        source_ids[species] = usage_id
        source_url = f"https://www.floraweb.de/php/biologie.php?suchnr={usage_id}&"
        common = {
            "species": species,
            "provider": "floraweb_biolflor_snapshot_2026_06_24",
            "url": source_url,
            "lineage": f"floraweb:name_usage_id:{usage_id}",
            "lineage_method": "original_floraweb_name_usage_id",
            "source_artifact": f"taxifydb-floraweb-raw-2026-06-24-sha256-{FLORAWEB_SHA256}",
            "source_file": path.name,
            "quality": "medium",
        }
        trait = ""
        axis = ""
        value = ""
        if label == "SI-Reaktion":
            trait, axis, value = (
                "self_incompatibility",
                "reproductive_assurance",
                _floraweb_si(raw),
            )
        elif label == "Befruchtungstyp":
            trait, axis, value = (
                "mating_system",
                "reproductive_assurance",
                _floraweb_mating(raw),
            )
        elif label == "Blumentyp (nach Kugler 1970)":
            trait, axis, value = (
                "floral_form",
                "floral_structural_complexity",
                _floraweb_form(raw),
            )
        elif label == "Bestäubung (Pollenvektoren)":
            trait, value = _floraweb_selfing_trait(raw)
            axis = "reproductive_assurance" if trait else ""
            folded = raw.casefold()
            if not folded.startswith(("nie ", "unbekannt ")):
                key = (species, "pollen_vector_mode")
                if "insektenbestäubung" in folded:
                    non_axis_by_species.setdefault(key, set()).add("biotic")
                    raw_values.setdefault(key, []).append(raw)
                if "windbestäubung" in folded:
                    non_axis_by_species.setdefault(key, set()).add("abiotic_wind")
                    raw_values.setdefault(key, []).append(raw)
        elif label == "Belohnung für Bestäuber":
            folded = raw.casefold()
            key = (species, "reward_type")
            if "nektar" in folded and not folded.startswith("kein "):
                non_axis_by_species.setdefault(key, set()).add("nectar")
                raw_values.setdefault(key, []).append(raw)
            if "pollen" in folded and not folded.startswith("kein "):
                non_axis_by_species.setdefault(key, set()).add("pollen")
                raw_values.setdefault(key, []).append(raw)
            if "öl" in folded and not folded.startswith("kein "):
                non_axis_by_species.setdefault(key, set()).add("oil")
                raw_values.setdefault(key, []).append(raw)
        if value:
            strict_rows.append(
                _record(
                    **common,
                    trait=trait,
                    axis=axis,
                    value=value,
                    source_key=f"{usage_id}:{label}:{raw}",
                    citation=(
                        "FloraWeb (Bundesamt für Naturschutz), carrying BiolFlor "
                        "traits of Klotz, Kühn & Durka (2002); archived snapshot 2026-06-24"
                    ),
                    excerpt=f"{label}: {raw}",
                )
            )

    supplemental: list[dict[str, str]] = []
    for (species, trait), states in sorted(non_axis_by_species.items()):
        value = (
            "mixed"
            if trait == "pollen_vector_mode" and len(states) > 1
            else "|".join(sorted(states))
        )
        usage_id = source_ids[species]
        supplemental.append(
            _record(
                species=species,
                trait=trait,
                axis="",
                value=value,
                provider="floraweb_biolflor_snapshot_2026_06_24",
                url=f"https://www.floraweb.de/php/biologie.php?suchnr={usage_id}&",
                source_key=f"{usage_id}:{trait}",
                citation=(
                    "FloraWeb (Bundesamt für Naturschutz), carrying BiolFlor "
                    "traits of Klotz, Kühn & Durka (2002); archived snapshot 2026-06-24"
                ),
                excerpt="; ".join(sorted(set(raw_values[(species, trait)]))),
                lineage=f"floraweb:name_usage_id:{usage_id}",
                lineage_method="original_floraweb_name_usage_id",
                source_artifact=f"taxifydb-floraweb-raw-2026-06-24-sha256-{FLORAWEB_SHA256}",
                source_file=path.name,
                quality="medium",
            )
        )
    return strict_rows, supplemental


def _require_hash(path: Path, expected: str, label: str) -> None:
    actual = _sha256(path)
    if actual != expected:
        raise ValueError(f"{label} SHA256 {actual} != pinned {expected}")


def pfaf_rows(path: Path) -> list[dict[str, str]]:
    _require_hash(path, PFAF_SHA256, "PFAF candidate export")
    source = pd.read_csv(path, dtype=str).fillna("")
    source = source.loc[
        source["status"].eq("accepted_self_fertile_statement")
        & source["identity_exact"].str.casefold().eq("true")
        & source["normalized_value"].eq("SC")
    ]
    rows: list[dict[str, str]] = []
    for item in source.to_dict("records"):
        species = _text(item["accepted_species"])
        url = _text(item["source_url"])
        rows.append(
            _record(
                species=species,
                trait="self_incompatibility",
                axis="reproductive_assurance",
                value="SC",
                provider="pfaf_ken_fern",
                url=url,
                source_key=url,
                citation="Plants For A Future species profile, compiled by Ken Fern",
                excerpt=_text(item["supporting_excerpt"]),
                lineage=f"ken-fern-useful-plants:species:{species.casefold()}",
                lineage_method="shared_ken_fern_species_lineage_across_pfaffern_mirrors",
                source_artifact=f"pfaf-live-pages-sha256-{PFAF_SHA256}",
                source_file=path.name,
                quality="medium",
                acceptance_contract="exact_species_positive_self_fertility_v1",
            )
        )
    return rows


def ken_fern_rows(path: Path) -> list[dict[str, str]]:
    _require_hash(path, KEN_FERN_SHA256, "Ken Fern candidate export")
    source = pd.read_csv(path, dtype=str).fillna("")
    source = source.loc[
        source["status"].eq("accepted_wild_self_fertile")
        & source["identity_exact"].str.casefold().eq("true")
        & source["family_exact"].str.casefold().eq("true")
        & source["wild_explicit"].str.casefold().eq("true")
    ]
    rows: list[dict[str, str]] = []
    for item in source.to_dict("records"):
        species = _text(item["accepted_species"])
        url = _text(item["source_url"])
        rows.append(
            _record(
                species=species,
                trait="self_incompatibility",
                axis="reproductive_assurance",
                value="SC",
                provider="ken_fern_useful_plants",
                url=url,
                source_key=url,
                citation="Ken Fern, Useful Tropical Plants / Useful Temperate Plants",
                excerpt=_text(item["supporting_excerpt"]),
                lineage=f"ken-fern-useful-plants:species:{species.casefold()}",
                lineage_method="shared_ken_fern_species_lineage_across_pfaffern_mirrors",
                source_artifact=f"ken-fern-live-pages-sha256-{KEN_FERN_SHA256}",
                source_file=path.name,
                quality="medium",
                acceptance_contract="exact_wild_species_positive_self_fertility_v1",
            )
        )
    return rows


def tree_of_sex_rows(path: Path, master: pd.DataFrame) -> list[dict[str, str]]:
    _require_hash(path, TREE_OF_SEX_SHA256, "Tree of Sex export")
    source = pd.read_csv(path, dtype=str).fillna("")
    source = source.loc[
        source["taxon_group"].str.casefold().eq("plants")
        & source["selfing"].ne("")
        & source["source_selfing"].ne("")
        & source["infraspecific"].eq("")
        & ~source["hybrid"].str.casefold().isin({"1", "true", "y", "yes"})
        & ~source["sexual_system"].str.casefold().eq("dioecy")
        & ~source["source_selfing"].str.contains("pfaf", case=False, na=False)
    ].copy()
    family_map = master.set_index("accepted_species")["family"].to_dict()
    source = source.loc[source["canonical_name"].isin(family_map)].copy()
    source = source.loc[
        [
            _text(family_map.get(species, "")).casefold() == _text(family).casefold()
            for species, family in zip(source["canonical_name"], source["family"], strict=True)
        ]
    ]
    value_map = {
        "self compatible": "SC",
        "self incompatible": "SI",
        "self compatible|self incompatible": "mixed_or_variable",
    }
    source["normalized"] = source["selfing"].str.casefold().map(value_map).fillna("")
    source = source.loc[source["normalized"].ne("")]
    rows: list[dict[str, str]] = []
    url = "https://datadryad.org/dataset/doi:10.5061/dryad.v1908"
    for item in source.to_dict("records"):
        species = _text(item["canonical_name"])
        citation = _text(item["source_selfing"])
        citation_key = hashlib.sha256(citation.casefold().encode("utf-8")).hexdigest()[:20]
        rows.append(
            _record(
                species=species,
                trait="self_incompatibility",
                axis="reproductive_assurance",
                value=_text(item["normalized"]),
                provider="tree_of_sex_dryad",
                url=url,
                source_key=f"{species}:{citation}",
                citation=f"Tree of Sex source_selfing: {citation}",
                excerpt=f"selfing: {_text(item['selfing'])}; source_selfing: {citation}",
                lineage=f"citation:{citation_key}:species:{species.casefold()}",
                lineage_method="underlying_source_selfing_citation_not_redistributor",
                source_artifact=f"tree-of-sex-taxifydb-sha256-{TREE_OF_SEX_SHA256}",
                source_file=path.name,
                acceptance_contract="published_database_exact_species_selfing_v1",
            )
        )
    return rows


def alien_plants_autogamy_rows(path: Path, eligible_names: set[str]) -> list[dict[str, str]]:
    _require_hash(path, ALIEN_PLANTS_AUTOGAMY_SHA256, "Alien Plants autogamy page")
    # The page explicitly labels these values as pollination type and glosses
    # autogamy as self-pollination.  It contains no autonomous fruit/seed-set
    # evidence, so the records remain discovery-only for the strict ledger.
    return []


def direct_literature_rows(path: Path, eligible_names: set[str]) -> list[dict[str, str]]:
    source = pd.read_csv(path, dtype=str).fillna("")
    required = {
        "accepted_species",
        "trait_name",
        "axis",
        "normalized_value",
        "quality",
        "source_url",
        "source_citation",
        "source_excerpt",
        "name_match_method",
        "source_lineage",
        "lineage_method",
        "source_artifact",
        "source_file",
    }
    missing = required - set(source.columns)
    if missing:
        raise ValueError(f"direct literature manifest missing columns: {sorted(missing)}")
    source = source.loc[source["accepted_species"].isin(eligible_names)].copy()
    rows: list[dict[str, str]] = []
    for item in source.to_dict("records"):
        species = _text(item["accepted_species"])
        rows.append(
            _record(
                species=species,
                trait=_text(item["trait_name"]),
                axis=_text(item["axis"]),
                value=_text(item["normalized_value"]),
                provider="direct_reproductive_literature_20260808",
                url=_text(item["source_url"]),
                source_key=f"{species}:{_text(item['source_lineage'])}",
                citation=_text(item["source_citation"]),
                excerpt=_text(item["source_excerpt"]),
                lineage=_text(item["source_lineage"]),
                lineage_method=_text(item["lineage_method"]),
                source_artifact=_text(item["source_artifact"]),
                source_file=_text(item["source_file"]),
                quality=_text(item["quality"]),
                name_match_method=_text(item["name_match_method"]),
                evidence_scope=(
                    "synonym_direct"
                    if _text(item["name_match_method"]).startswith("synonym_")
                    else "species_direct"
                ),
                acceptance_contract="quoted_original_reproductive_study_v1",
            )
        )
    return rows


def _sample_provider(evidence: pd.DataFrame, target: int = 200) -> pd.DataFrame:
    if len(evidence) <= target:
        return evidence.copy()
    pieces = []
    groups = list(evidence.groupby("trait_name", sort=True))
    remaining = target
    for index, (_, group) in enumerate(groups):
        if index == len(groups) - 1:
            take = min(remaining, len(group))
        else:
            take = min(len(group), max(10, round(target * len(group) / len(evidence))))
            take = min(take, remaining - 10 * (len(groups) - index - 1))
        pieces.append(group.sample(n=take, random_state=AUDIT_RANDOM_STATE + index))
        remaining -= take
    if remaining:
        used = set(pd.concat(pieces)["source_record_id"])
        rest = evidence.loc[~evidence["source_record_id"].isin(used)]
        pieces.append(
            rest.sample(n=min(remaining, len(rest)), random_state=AUDIT_RANDOM_STATE + 99)
        )
    return pd.concat(pieces, ignore_index=True)


def build(
    *,
    grassbase_csv: Path,
    nhm_root: Path,
    baseflor_xlsx: Path,
    florabase_csv: Path,
    floraweb_csv: Path,
    pfaf_csv: Path,
    ken_fern_csv: Path,
    tree_of_sex_csv: Path,
    alien_plants_autogamy_html: Path,
    direct_literature_csv: Path,
    master_csv: Path,
    current_coverage_csv: Path,
    current_lineages_csv: Path,
    output_dir: Path,
) -> dict[str, object]:
    master = pd.read_csv(master_csv, dtype=str).fillna("")
    master_names = set(master["accepted_species"])
    coverage = pd.read_csv(current_coverage_csv, usecols=["accepted_species"], dtype=str).fillna("")
    strict_names = set(coverage["accepted_species"])
    if len(strict_names) != 106_295:
        raise ValueError(f"strict coverage has {len(strict_names)} species, expected 106295")
    eligible_names = master_names & strict_names
    lineages = pd.read_csv(current_lineages_csv, dtype=str).fillna("")
    current_pairs = _current_pairs(lineages)
    floraweb_strict, supplemental = floraweb_rows(floraweb_csv, eligible_names)
    records = (
        grassbase_rows(grassbase_csv)
        + nhm_efloras_rows(nhm_root, lineages)
        + baseflor_rows(baseflor_xlsx, eligible_names)
        + florabase_rows(florabase_csv)
        + floraweb_strict
        + pfaf_rows(pfaf_csv)
        + ken_fern_rows(ken_fern_csv)
        + tree_of_sex_rows(tree_of_sex_csv, master)
        + alien_plants_autogamy_rows(alien_plants_autogamy_html, eligible_names)
        + direct_literature_rows(direct_literature_csv, eligible_names)
    )
    inventory = pd.DataFrame(records, columns=EVIDENCE_COLUMNS).fillna("")
    inventory = inventory.loc[inventory["accepted_species"].isin(eligible_names)].copy()
    inventory = inventory.drop_duplicates(
        ["accepted_species", "trait_name", "normalized_value", "source_lineage"]
    ).sort_values(["source_provider", "trait_name", "accepted_species", "source_record_id"])
    inventory["novel_species_trait"] = [
        (species, trait) not in current_pairs
        for species, trait in zip(
            inventory["accepted_species"], inventory["trait_name"], strict=True
        )
    ]
    evidence = (
        inventory.loc[inventory["novel_species_trait"]]
        .drop(columns="novel_species_trait")
        .reset_index(drop=True)
    )
    if evidence["source_record_id"].duplicated().any():
        raise ValueError("source_record_id is not unique")

    audit_parts = []
    for provider, group in evidence.groupby("source_provider", sort=True):
        sampled = _sample_provider(group, target=200)
        sampled = sampled.rename(
            columns={
                "source_provider": "provider",
                "source_record_id": "candidate_id",
                "source_excerpt": "exact_supporting_quote",
            }
        )
        sampled["accepted_correct"] = ""
        sampled["cultivar_status"] = "wild_or_unspecified_species_record"
        sampled["reviewer"] = ""
        sampled["reviewed_at_utc"] = ""
        sampled["audit_reason"] = ""
        audit_parts.append(sampled)
    audit = pd.concat(audit_parts, ignore_index=True).sort_values(
        ["provider", "trait_name", "accepted_species", "candidate_id"]
    )

    output_dir.mkdir(parents=True, exist_ok=True)
    inventory.to_csv(output_dir / "scale_source_full_inventory.csv.gz", index=False)
    evidence.to_csv(output_dir / "scale_source_incremental_evidence.csv.gz", index=False)
    audit.to_csv(output_dir / "scale_source_manual_audit.csv", index=False)
    pd.DataFrame(supplemental, columns=EVIDENCE_COLUMNS).to_csv(
        output_dir / "scale_source_non_axis_candidates.csv.gz", index=False
    )

    provider_rows = []
    for provider, group in evidence.groupby("source_provider", sort=True):
        provider_rows.append(
            {
                "source_provider": provider,
                "evidence_rows": len(group),
                "species": int(group["accepted_species"].nunique()),
                "species_trait": len(group.drop_duplicates(["accepted_species", "trait_name"])),
                "traits": sorted(group["trait_name"].unique()),
                "audit_rows": int(audit["provider"].eq(provider).sum()),
            }
        )
    summary: dict[str, object] = {
        "contract": "scale_structured_flora_source_package_v1",
        "created_at_utc": datetime.now(timezone.utc).isoformat(),  # noqa: UP017
        "current_direct_species_trait": len(current_pairs),
        "strict_universe_species": len(strict_names),
        "full_inventory_rows": len(inventory),
        "full_inventory_species_trait": len(
            inventory.drop_duplicates(["accepted_species", "trait_name"])
        ),
        "incremental_evidence_rows": len(evidence),
        "incremental_species_trait": len(
            evidence.drop_duplicates(["accepted_species", "trait_name"])
        ),
        "incremental_species": int(evidence["accepted_species"].nunique()),
        "non_axis_candidate_rows": len(supplemental),
        "audit_rows": len(audit),
        "providers": provider_rows,
        "baseflor_sha256": BASEFLOR_SHA256,
        "input_files": {
            f"grassbase/{grassbase_csv.name}": {"sha256": _sha256(grassbase_csv)},
            **{
                path.name: {"sha256": _sha256(path)}
                for path in sorted(nhm_root.glob("*_exact_master_records.csv.gz"))
            },
            f"baseflor/{baseflor_xlsx.name}": {"sha256": _sha256(baseflor_xlsx)},
            f"florabase/{florabase_csv.name}": {"sha256": _sha256(florabase_csv)},
            f"floraweb/{floraweb_csv.name}": {"sha256": _sha256(floraweb_csv)},
            f"pfaf/{pfaf_csv.name}": {"sha256": _sha256(pfaf_csv)},
            f"ken_fern/{ken_fern_csv.name}": {"sha256": _sha256(ken_fern_csv)},
            f"tree_of_sex/{tree_of_sex_csv.name}": {"sha256": _sha256(tree_of_sex_csv)},
            f"alien_plants/{alien_plants_autogamy_html.name}": {
                "sha256": _sha256(alien_plants_autogamy_html)
            },
            f"direct_literature/{direct_literature_csv.name}": {
                "sha256": _sha256(direct_literature_csv)
            },
            f"baseline/{current_lineages_csv.name}": {"sha256": _sha256(current_lineages_csv)},
            f"baseline/{current_coverage_csv.name}": {"sha256": _sha256(current_coverage_csv)},
        },
        "source_access": {
            "kew_grassbase": "https://static1.kew.org/data/grasses-db/sppindex.htm",
            "nhm_adept": "https://data.nhm.ac.uk/dataset/angiosperm-functional-traits-extracted-from-botanical-descriptions",
            "baseflor": "https://www.tela-botanica.org/ressources/donnees/telechargements/",
            "florabase": "https://florabase.dbca.wa.gov.au/",
            "floraweb_snapshot": "https://github.com/gcol33/taxifydb/releases/download/scrape-snapshots-2026.06/floraweb_raw_2026-06-24.csv",
            "pfaf": "https://pfaf.org/",
            "ken_fern": [
                "https://tropical.theferns.info/",
                "https://temperate.theferns.info/",
            ],
            "tree_of_sex": "https://datadryad.org/dataset/doi:10.5061/dryad.v1908",
            "alien_plants_greece": "https://www.alienplants.gr/pollination-type/autogamy",
        },
        "promotion_performed": False,
        "strict_exclusions": [
            "source pairs already represented by direct evidence",
            "NHM sex system and reward outside strict axes",
            "NHM pollination outside strict structural and reproductive axes",
            "Baseflor sexual system outside strict reproductive assurance",
            "Baseflor non-autogamous pollen-vector values outside strict axes",
            "grass bract glume lemma and fruit colours",
            "cultivar hybrid and non-species ranks",
            "PFAF apomixis and dioecy category conflicts",
            "Ken Fern cultivated-only and family-mismatched records",
            "Tree of Sex PFAF redistributions and non-exact family matches",
        ],
    }
    (output_dir / "scale_source_package_summary.json").write_text(
        json.dumps(summary, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return summary


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--grassbase-csv", type=Path, required=True)
    parser.add_argument("--nhm-root", type=Path, required=True)
    parser.add_argument("--baseflor-xlsx", type=Path, required=True)
    parser.add_argument("--florabase-csv", type=Path, required=True)
    parser.add_argument("--floraweb-csv", type=Path, required=True)
    parser.add_argument("--pfaf-csv", type=Path, required=True)
    parser.add_argument("--ken-fern-csv", type=Path, required=True)
    parser.add_argument("--tree-of-sex-csv", type=Path, required=True)
    parser.add_argument("--alien-plants-autogamy-html", type=Path, required=True)
    parser.add_argument("--direct-literature-csv", type=Path, required=True)
    parser.add_argument("--master-csv", type=Path, required=True)
    parser.add_argument("--current-coverage-csv", type=Path, required=True)
    parser.add_argument("--current-lineages-csv", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(build(**vars(args)), indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
